[project]
name = "mcp-server-tracker-remote"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aisqlite>=1.1.0",
    "fastmcp>=2.13.1",
]
